FROM ubuntu:18.04
RUN dpkg --add-architecture i386 && \
	apt-get update && \
	apt-get install -y wine32 zenity wget && \
	wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && \
	chmod +x winetricks 