FROM nvidia/opengl:1.2-glvnd-runtime-ubuntu20.04

ENV USER=root
ENV PASSWORD=password1
ENV DEBIAN_FRONTEND=noninteractive 
ENV DEBCONF_NONINTERACTIVE_SEEN=true
RUN apt-get update && \
	echo "tzdata tzdata/Areas select America" > ~/tx.txt && \
	echo "tzdata tzdata/Zones/America select New York" >> ~/tx.txt && \
	debconf-set-selections ~/tx.txt && \
	apt-get install -y gnupg apt-transport-https wget software-properties-common ratpoison libglu1-mesa mesa-utils xauth xterm x11-utils xorg tightvncserver

	
RUN	wget https://phoenixnap.dl.sourceforge.net/project/virtualgl/2.6.3/virtualgl_2.6.3_amd64.deb && \
	wget https://phoenixnap.dl.sourceforge.net/project/turbovnc/2.2.4/turbovnc_2.2.4_amd64.deb && \
	dpkg -i virtualgl_*.deb && \
	dpkg -i turbovnc_*.deb && \
	mkdir ~/.vnc/ && \
	echo $PASSWORD | vncpasswd -f > ~/.vnc/passwd && \
	chmod 0600 ~/.vnc/passwd && \
	echo "set border 1" > ~/.ratpoisonrc  && \
	echo "exec glxgears">> ~/.ratpoisonrc
EXPOSE 5901
CMD /opt/TurboVNC/bin/vncserver && tail -f /dev/null


